
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/CMakeInstall/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:206 (message)"
      - "CMakeLists.txt:19 (project)"
    message: |
      The target system is: Windows -  - 
      The host system is: Windows - 10.0.19045 - AMD64
...
